package pl.motyka.mateusz.klaser;

public enum Rarity {
	RARE, COMMON, UNCOMMON, RARE_HOLO, RARE_HOLO_LV_X, RARE_ULTRA, RARE_RAINBOW, RARE_HOLO_EX, RARE_PRIME, RARE_ACE, RARE_HOLO_GX, LEGEND, RARE_BREAK;
	public static final Rarity[] ALL = {
			RARE, COMMON, UNCOMMON, RARE_HOLO, RARE_HOLO_LV_X, RARE_ULTRA, RARE_RAINBOW, RARE_HOLO_EX, RARE_PRIME, RARE_ACE, RARE_HOLO_GX, LEGEND, RARE_BREAK
    };
}
